name = "crimson-bar-9107"
main = "src/worker.js"
compatibility_date = "2026-02-19"
workers_dev = true

[vars]
GOOGLE_SHEET_ID = "1ukXTu8PXWHGe4Fzg5rA424BmN6Bi3FPAWwA12QybNpI"
GOOGLE_META_TAB = "meta"
GOOGLE_POINTS_TAB = "points"
GOOGLE_LIVE_PRICES_TAB = "live_prices"
GOOGLE_BTC_PRICE_TAB = "BTC Price"
GOOGLE_TREASURIES_TAB = "Treasuries"
GOOGLE_CIRCULATING_TAB = "Circulating BTC"
GOOGLE_LIQUIDATIONS_TAB = "Liquidations"
GOOGLE_OWNERSHIP_TAB = "Distribution"
CACHE_TTL_SECONDS = "120"

[assets]
directory = "./public"
binding = "ASSETS"
